name: Code Coverage

on: [pull_request]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        # node-version: [14.x, 16.x, 18.x]
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Dependencies
      run: npm ci

    - name: Link Dependencies
      run: npx lerna link 

    - name: Install dependencies
      run: npm ci

    - name: Build Packages
      run: npm run build

    - name: Run the tests
      run: npm test -- --coverage

    - name: Coverage Badge
      run: npm run test:coverage
