name: Publish Packages
on:
  pull_request:
    types: [closed]
    branches:
      - main 
      - development 
      - beta
      - stable

jobs:
  publish:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:

    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}
        fetch-depth: "0"
        token: ${{ secrets.GITHUB_TOKEN }} # this token is available by default

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Conifrm NPM Publishability
      run: npm whoami # will throw and exit if npm is not ready to publish

    - name: Install dependencies
      run: npm ci

    - name: Link Dependencies
      run: npx lerna link 

    - name: Build Packages
      run: npm run build

    - name: "Configure Git User"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"
    
    - name: Set version and branch
      run: |
        export BRANCH=${GITHUB_REF##*/}
        echo "Branch: $BRANCH"
        echo "BRANCH=$BRANCH" >> $GITHUB_ENV
    - name: "Version"
      run: |
        if [[ "$BRANCH" == "main" ]]; then
          npm run version:major
        else if [[ "$BRANCH" == "beta" ]]; then
          npm run version:minor
        else if [[ "$BRANCH" == "development" ]]; then
          npm run version:patch
        else
          npm run version:prerelease
        fi
    - name: "Publish"
      run: |
        npm run publish