name: Publish Packages
on:
  pull_request:
    # types: [closed]
    branches:
      - main
      - stable
      - feature/publish-automation
jobs:
  publish:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: "0"
        token: ${{ secrets.GITHUB_TOKEN }} # this token is available by default

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Conifrm NPM Publishability
      run: npm whoami # will throw and exit if npm is not ready to publish

    - name: Install dependencies
      run: npm ci

    - name: Link Dependencies
      run: npx lerna link 

    - name: Build Packages
      run: npm run build

    - name: "Version and publish" # Interesting step
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config user.name "${{ github.actor }}"
        git config user.email "${{ github.actor}}@users.noreply.github.com"

        if [[ ${{ github.base_ref }} = development ]]; then
          npx lerna version --conventional-commits --conventional-prerelease --preid beta --yes
        elif [[ ${{ github.base_ref }} = main ]]; then 
          npx lerna version --conventional-commits --conventional-graduate --yes
        else
          npx lerna version patch --conventional-commits --conventional-prerelease --preid alpha --yes
        fi

        npm run publish:lerna